# Generated by Django 4.1.3 on 2022-11-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_title', models.CharField(max_length=50)),
                ('map_image', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
