# Generated by Django 4.1.3 on 2022-11-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_map_image_height_map_image_width_alter_map_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
