# Generated by Django 4.1.3 on 2022-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='xCoord',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='yCoord',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
