# Generated by Django 4.1.3 on 2022-12-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_location_xcoord_location_ycoord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='map',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='map',
            name='map_image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
