# Generated by Django 4.1.3 on 2022-12-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_note'),
        ('maps', '0006_remove_map_image_height_remove_map_image_width_and_more'),
    ]

    operations = [
    ]
