# Generated by Django 4.1.3 on 2022-12-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_name',
            field=models.CharField(max_length=100),
        ),
    ]
