# Generated by Django 4.1.3 on 2022-12-21 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_campaign_title_alter_character_char_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.CharField(choices=[('Artificer', 'Artificer'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='char_desc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='char_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
