# Generated by Django 4.1.3 on 2022-12-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_character_char_class_character_char_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_lineage',
            field=models.CharField(choices=[('Aarakockra', 'Aaracokra'), ('Aasimar', 'Aasimar'), ('Bugbear', 'Bugbear'), ('Centaur', 'Centaur'), ('Changeling', 'Changeling'), ('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Fairy', 'Fairy'), ('Firbolg', 'Firbolg'), ('Air Genasi', ' Air Genasi'), ('Earth Genasi', ' Earth Genasi'), ('Fire Genasi', ' Fire Genasi'), ('Water Genasi', ' Water Genasi'), ('Gnome', 'Gnome'), ('Goblin', 'Goblin'), ('Golaith', 'Goliath'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Halfling', 'Halfling'), ('Harengon', 'Harengon'), ('Human', 'Human'), ('Kenku', 'Kenku'), ('Lizardfolk', 'Lizardfolk'), ('Orc', 'Orc'), ('Tabaxi', 'Tabaxi'), ('Tiefling', 'Tiefling'), ('Tortle', 'Tortle'), ('Warforged', 'Warforged'), ('Yuan-Ti', 'Yuan-Ti')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1),
        ),
    ]
