# Generated by Django 4.1.3 on 2022-12-22 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0014_character_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maps.campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
