# Generated by Django 4.1.3 on 2023-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='xCoord',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='yCoord',
            field=models.FloatField(),
        ),
    ]
