# Generated by Django 4.1.3 on 2023-01-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_alter_location_xcoord_alter_location_ycoord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='char_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_lineage',
        ),
    ]
